# -*- coding: utf-8 -*-
"""Cópia de Atividade 3 - Simulação de Monte Carlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdeXFOS_Re4v8JYNHc_QVoMQWp894vwa

# **Simulação de Monte Carlo - Caso TechToy**
1. **Introdução e Contexto**

A empresa TechToy está prestes a lançar um novo drone no mercado. A diretoria está em dúvida entre duas estratégias de lançamento e contratou você, analista de dados, para realizar uma Simulação de Monte Carlo.

O objetivo é entender não apenas o lucro esperado, mas o risco de prejuízo de cada decisão.

As Estratégias:
Estratégia A (Conservadora): Foca em um público de nicho, com preço mais alto e vendas mais previsíveis.

Estratégia B (Agressiva): Foca em escala, com preço menor, mas com custos de produção e volume de vendas muito mais incertos.

**2. Base de Dados e Parâmetros**

Execute a célula abaixo para carregar as bibliotecas necessárias e os parâmetros oficiais fornecidos pelo departamento financeiro.
"""

import numpy as np
import matplotlib.pyplot as plt

# Configurações da Simulação
N_SIMULACOES = 10000

# --- PARÂMETROS ESTRATÉGIA A ---
vendas_media_a = 500
vendas_desvio_a = 50
custo_min_a = 600
custo_max_a = 700
preco_venda_a = 1200
investimento_fixo_a = 50000

# --- PARÂMETROS ESTRATÉGIA B ---
vendas_media_b = 800
vendas_desvio_b = 250
custo_min_b = 400
custo_max_b = 800
preco_venda_b = 1000
investimento_fixo_b = 150000

print("Parâmetros carregados com sucesso!")

"""3. Desafio

**1: Modelagem do Lucro**

Crie uma função ou um script que utilize os parâmetros acima para gerar 10.000 resultados possíveis de lucro para cada estratégia.Dicas:Para as Vendas, use uma distribuição Normal: np.random.normal(media, desvio, N_SIMULACOES).Para o Custo Unitário, use uma distribuição Uniforme: np.random.uniform(min, max, N_SIMULACOES).

A fórmula do lucro é:

$Lucro = (Vendas \times Preço) - (Vendas \times Custo\_Unitário) - Investimento\_Fixo$
"""

import numpy as np
import matplotlib.pyplot as plt

# Configurações da Simulação
N_SIMULACOES = 10000

# PARÂMETROS ESTRATÉGIA A
vendas_media_a = 500
vendas_desvio_a = 50
custo_min_a = 600
custo_max_a = 700
preco_venda_a = 1200
investimento_fixo_a = 50000

# PARÂMETROS ESTRATÉGIA B
vendas_media_b = 800
vendas_desvio_b = 250
custo_min_b = 400
custo_max_b = 800
preco_venda_b = 1000
investimento_fixo_b = 150000

# SIMULAÇÃO ESTRATÉGIA A

vendas_a = np.random.normal(vendas_media_a, vendas_desvio_a, N_SIMULACOES)
custo_a = np.random.uniform(custo_min_a, custo_max_a, N_SIMULACOES)

lucro_a = (vendas_a * preco_venda_a) - (vendas_a * custo_a) - investimento_fixo_a

# SIMULAÇÃO ESTRATÉGIA B

vendas_b = np.random.normal(vendas_media_b, vendas_desvio_b, N_SIMULACOES)
custo_b = np.random.uniform(custo_min_b, custo_max_b, N_SIMULACOES)

lucro_b = (vendas_b * preco_venda_b) - (vendas_b * custo_b) - investimento_fixo_b

plt.figure(figsize=(12,5))

plt.hist(lucro_a, bins=50, alpha=0.6, label='Estratégia A')
plt.hist(lucro_b, bins=50, alpha=0.6, label='Estratégia B')

plt.title('Distribuição de Lucros - Simulação Monte Carlo')
plt.xlabel('Lucro')
plt.ylabel('Frequência')
plt.legend()

plt.show()

# MÉTRICAS IMPORTANTES

print("Estratégia A:")
print(f"Lucro médio: {np.mean(lucro_a):.2f}")
print(f"Probabilidade de prejuízo: {np.mean(lucro_a < 0)*100:.2f}%")

print("\nEstratégia B:")
print(f"Lucro médio: {np.mean(lucro_b):.2f}")
print(f"Probabilidade de prejuízo: {np.mean(lucro_b < 0)*100:.2f}%")

"""**2: Visualização dos Resultados**

Gere um histograma comparando as duas estratégias. O gráfico deve ajudar a diretoria a visualizar onde o lucro se concentra e onde estão os riscos de perda (valores abaixo de zero).
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))

# Histograma Estratégia A
plt.hist(lucro_a, bins=50, alpha=0.6, label='Estratégia A')

# Histograma Estratégia B
plt.hist(lucro_b, bins=50, alpha=0.6, label='Estratégia B')

plt.axvline(x=0)

plt.title('Simulação de Monte Carlo - Comparação de Lucros')
plt.xlabel('Lucro')
plt.ylabel('Frequência')

plt.legend()

plt.grid()

plt.show()

"""**3: Cálculo de Probabilidades**
Calcule e exiba as seguintes métricas para cada estratégia:

Média de Lucro.

Probabilidade de Prejuízo (porcentagem de simulações onde o lucro foi < 0).
"""